### ISSUE TITLE
Bring up to date with GHC 9.0

### ISSUE THREAD

**Issue by ejconlon** [mvv/data-sword#1]
Hello and thanks for the nice library - I did a hack job on bringing the library up to date with GHC 9 but in the process removed a bunch of back-compat CPP. If you have any interest in the changes, you can find them here: https://github.com/ejconlon/data-sword .

**Comment by mvv** [comment]
Thanks for bringing the issue to my attention. I've just uploaded version `0.2.0.3`, which is compatible with GHC `9.{0,2,4}`, on Hackage.
